debug: false
host: 'localhost'
http_port: 8000
websocket_port: 9001
html_file: 'app/static/overlay.html'
output_dir: 'output'

obs:
  host: 'localhost'
  port: 4455
  password: 'sVGMUL9acPkBYvCf'

capture:
  mode: 'direct_webcam'  # 'obs_websocket' or 'direct_webcam'
  width: 1280
  height: 720
  fps: 1.8

yolo:
  model: 'models/best.mlpackage'
  confidence_threshold: 0.70
  overlap_threshold: 0.80

board_processor:
  vertical_alignment_threshold: 0.20
  min_frames_to_show: 3
  min_ms_to_show: 1200
  min_frames_to_remove: 6
  min_ms_to_remove: 4200