host: 'localhost'
http_port: 8000
websocket_port: 9001
html_file: 'app/static/overlay.html'
output_dir: 'output'

obs:
  host: 'localhost'
  port: 4455
  password: 'your_password_here'

capture:
  mode: 'direct_webcam'  # 'obs_websocket' or 'direct_webcam'
  width: 1280
  height: 720
  fps: 2

yolo:
  model: 'models/best.pt'

debug: false